### ISSUE TITLE
Bagaimana

### ISSUE THREAD

**Issue by samsularifin93** [samsularifin1993/Test#2]
Keren gak nih?
Keren aja

**Comment by samsularifin1993** [comment]
[Hahahaha](https://github.com/samsularifin1993/Test/issues/2#issue-354800553)

@samsularifin93 
#1 

Keren bang

**Comment by samsularifin93** [comment]
https://github.com/samsularifin1993/Test/issues/2#issuecomment-416645331
Bisa dong

**Comment by samsularifin93** [comment]
Sudah
